services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5432:5432
    volumes:
      - ./data_postgres:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mishal@mazin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
  dataloader:
    image: taxi_ingest:v001 
    command: ["--user=root", "--password=root", "--host=pgdatabase", "--port=5432", "--db=ny_taxi","--tb=yellow_taxi_data", "--url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-09.parquet"]
